# Generated by Django 3.0.5 on 2020-04-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tee',
            name='slope',
            field=models.IntegerField(),
        ),
    ]
