# Generated by Django 3.0.5 on 2020-04-05 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0002_tees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=20)),
                ('slope', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handicap.Course')),
            ],
        ),
        migrations.DeleteModel(
            name='Tees',
        ),
    ]
