# Generated by Django 3.0.5 on 2020-04-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0002_auto_20200419_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
