# Generated by Django 3.0.5 on 2020-04-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0003_round_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
