# Generated by Django 3.0.5 on 2020-04-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0003_auto_20200405_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_verified',
        ),
        migrations.AddField(
            model_name='course',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
