# Generated by Django 3.0.5 on 2020-04-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0004_course_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='zip_Code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
