# Generated by Django 3.0.5 on 2020-04-05 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0004_auto_20200405_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='tee',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tee',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=4)),
                ('differential', models.CharField(blank=True, max_length=5)),
                ('date_played', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handicap.Course')),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handicap.Tee')),
            ],
        ),
    ]
