# Generated by Django 3.0.5 on 2020-04-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0005_auto_20200423_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='phone',
        ),
    ]
