# Generated by Django 3.0.5 on 2020-04-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0006_auto_20200416_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=20)),
                ('date_added', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=4)),
                ('differential', models.CharField(blank=True, max_length=5)),
                ('date_played', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handicap.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Tee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=20)),
                ('slope', models.CharField(max_length=20)),
                ('date_added', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handicap.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='course',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='tee',
        ),
        migrations.RemoveField(
            model_name='tees',
            name='course',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Rounds',
        ),
        migrations.DeleteModel(
            name='Tees',
        ),
        migrations.AddField(
            model_name='round',
            name='tee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handicap.Tee'),
        ),
    ]
