# Generated by Django 3.0.5 on 2020-04-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0007_remove_course_date_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tee',
            name='date_modified',
        ),
    ]
