# Generated by Django 3.0.5 on 2020-04-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0007_auto_20200416_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='differential',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
