# Generated by Django 3.0.5 on 2020-04-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0008_auto_20200417_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='differential',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
