# Generated by Django 3.0.5 on 2020-04-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0008_remove_tee_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='tee',
            name='par',
            field=models.IntegerField(default=72),
        ),
    ]
