# Generated by Django 3.0.5 on 2020-04-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0009_tee_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='tee',
            name='length',
            field=models.CharField(default='- yards', max_length=20),
        ),
    ]
