# Generated by Django 3.0.7 on 2020-11-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0010_tee_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='user',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
